osrs_site/osrs_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('prices/', include('prices.urls')),
    path('admin/', admin.site.urls),
    path('prices/quick/', include('prices.urls'))
]

osrs_site/prices/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.search_item_price, name='Price look up'),
    path('quick/all', views.quick_flips_all, name='All Quick Flips'),
    path('quick/tables', views.quick_flips_db, name='Table view of Quick Flips'),
    path('quick/<str:item>/', views.single_table, name='Item Table'),
    path('alchemy', views.high_alc_calculator, name='High Alc Calc')
]

osrs_site/prices/models.py
from django.db import models


class HighAlc(models.Model):
    item_name = models.CharField(max_length=100)
    profit = models.PositiveIntegerField(verbose_name="profit")

    class Meta:
        pass


class QuickFlips(models.Model):
    item_name = models.CharField(max_length=100, verbose_name='Item Name')
    profit = models.IntegerField(verbose_name='Item Profit')
    item_price = models.PositiveIntegerField()

    class Meta:
        pass

    def __str__(self):
        return self.item_name + str(self.profit)


class Ingredient(models.Model):
    item_name = models.CharField(max_length=100)
    item_price = models.PositiveIntegerField(default=1)
    parent_item = models.ForeignKey(QuickFlips, on_delete=models.CASCADE)
    profit = models.IntegerField()

    def __str__(self):
        return self.item_name + str(self.item_price) + str(self.parent_item) + str(self.profit)

osrs_site/prices/forms.py
# listings/forms.py
from django import forms
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponse
class ItemQuery(forms.Form):
		item_id = forms.CharField(required=True)

osrs_site/prices/views.py
from django.shortcuts import render
from django_tables2 import MultiTableMixin, RequestConfig, SingleTableMixin, SingleTableView
import urllib

import get_price
from prices.forms import ItemQuery
from .tables import HighAlcTable, AllFlipsTable, FlipsTable
from .models import HighAlc, QuickFlips, Ingredient
import quick_money
import high_alc_calc


def search_item_price(request):
    if request.method == 'POST':  # only runs when form was filled out
        # create an instance of our form, and fill it with the POST data
        form = ItemQuery(request.POST)
        if form.is_valid():  # checks that the request was valid
            queried_data = get_price.ItemData(
                request.POST['item_id']).grab_data()  # passes string from form into grab_data to get item price
            if queried_data:
                return render(request, 'prices_page.html',
                              {'item_exists': True, 'item_data': queried_data, 'form': form})
            else:
                return render(request, 'prices_page.html', {'item_exists': False, 'form': form})
    form = ItemQuery()
    # if it makes it this far it must be GET method so pass in nothing and load template
    # initiate form to take user input
    return render(request, 'prices_page.html', {'item_exists': True, 'form': form})


def create_high_alc_data(force=False):
    if not HighAlc.objects or force:
        alc = high_alc_calc.alc_profit()
        sorted_alc = high_alc_calc.sort_alc_list(alc)
        for key in sorted_alc:
            HighAlc.objects.create(item_name=key, profit=sorted_alc[key])


def high_alc_calculator(request):
    table = HighAlcTable(HighAlc.objects.all())
    RequestConfig(request, paginate={'per_page': 15}).configure(table)

    return render(request, 'high_alc_calc.html', {
        'table': table
    }
                  )


def single_table(request, item):
    quick_money.build_profits_db(quick_money.update_flip_list())
    item = item.replace('+', ' ')
    for parent_object in QuickFlips.objects.filter(item_name=item):
        items = Ingredient.objects.filter(parent_item=parent_object.id)
        table = FlipsTable(items)
    return render(request, 'quick_money.html', {
        'tables': [table]  # Tables variable and list format is used so that the same html template can be used for all
    })


def quick_flips_all(request):
    quick_money.build_profits_db(quick_money.update_flip_list())
    tables_list = [AllFlipsTable(QuickFlips.objects.all())]
    import pdb;
    pdb.set_trace()
    return render(request, 'quick_money.html', {
        'tables': tables_list
    }
                  )


def quick_flips_db(request):
    tables_list = []
    quick_money.build_profits_db(quick_money.update_flip_list())
    for parent_object in QuickFlips.objects.all():
        # print(Ingredient.objects.filter(parent_item=parent_object.id))
        items = Ingredient.objects.filter(parent_item=parent_object.id)

        tables_list.append(FlipsTable(items))
        # total = items.annotate(Sum('item_price'))
    return render(request, 'quick_money.html', {
        'tables': tables_list,
    }
                  )

osrs_site/prices/templates/high_alc_calc.html
{% load static %}
{% load django_tables2 %}


{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cyborg/bootstrap.min.css" integrity="sha384-nEnU7Ae+3lD52AK+RGNzgieBWMnEfgTbRHIwEvp1XXPdqdO6uLTd/NwXbzboqjc2" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
{% csrf_token %}
{%include 'navbar.html' %}
{% endblock %}
{% render_table table %}
{{ items }}

osrs_site/prices/templates/list_table.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="ui container table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="ui celled table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                    <tr>
                    {% for column in table.columns %}
                        <th {{ column.attrs.th.as_html }}>
                            {% if column.orderable %}
                                <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                            {% else %}
                                {{ column.header }}
                            {% endif %}
                        </th>
                    {% endfor %}
                    </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                        {% if cell == row.cells.item_name %}
                            <td {{ column.attrs.td.as_html }}><a href="/prices/quick/{{cell}}">{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</a></td>
                        {% else %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endif %}
                            {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                    <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                {% if table.has_footer %}
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
                {% endif %}
                {% block pagination %}
                    {% if table.page and table.paginator.num_pages > 1 %}
                    <tr>
                    <th colspan="{{ table.columns|length }}">
                        <div class="ui right floated pagination menu">

                            <ul class="pagination">
                            {% if table.page.has_previous %}
                                {% block pagination.previous %}
                                <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                                    &laquo;
                                </a>
                                {% endblock pagination.previous %}
                            {% endif %}

                            {% if table.page.has_previous or table.page.has_next %}
                                {% block pagination.range %}
                                    {% for p in table.page|table_page_range:table.paginator %}
                                        {% if p == '...' %}
                                            <a href="#" class="item">{{ p }}</a>
                                        {% else %}
                                            <li class="page-item {% if p == table.page.number %}active{% endif %}">
                                            <a href="{% querystring table.prefixed_page_field=p %}" class="page-link">
                                                {{ p }}
                                            </a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                {% endblock pagination.range %}
                            {% endif %}

                            {% if table.page.has_next %}
                                {% block pagination.next %}
                                <li class="page-item">
                                <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                                    &raquo;
                                </a>
                                </li>
                                {% endblock pagination.next %}
                            {% endif %}
                        </div>
                    </th>
                    </tr>
                    {% endif %}
                </ul>
                {% endblock pagination %}
            </tfoot>
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}
</div>
{% endblock table-wrapper %}

osrs_site/prices/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="#">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

osrs_site/prices/templates/prices_page.html
<!doctype html>
<html lang="en">
{% block head %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ title }}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cyborg/bootstrap.min.css" integrity="sha384-nEnU7Ae+3lD52AK+RGNzgieBWMnEfgTbRHIwEvp1XXPdqdO6uLTd/NwXbzboqjc2" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
{% endblock %}
<body style="background-color:darkgrey;">

<p>Let's get this bread</p>
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<form method='post'>
{% csrf_token %}
<p>
<div class="input-group mb-3">
      <input type="text" name='item_id' required id='id_item_id' class="form-control" placeholder="Item Name" aria-label='123' aria-describedby="button-addon2">
<button class="btn btn-primary" type="button" id="button-addon2" value='Submit'>Search</button>
</div></form></p>
{%if item_data%}
	<img src = {{ item_data.icon }} >
	<p>{{ item_data.name }} Sell price: {{ item_data.low }}gp and Buy Price: {{item_data.high}} at <br></br> {%now "G:i" %} Last Refreshed </p>
{% endif%}
{% if not item_exists %}
<div class="alert alert-dismissible alert-danger">
  <button type="submit" class="btn-close" data-bs-dismiss="alert"></button>
  <strong>Oh snap!</strong> <a href="#" class="alert-link">{{ request.POST.item_id }} </a>  cannot be found check your spelling and try again!
  </div>
{% endif %}

</html>

osrs_site/prices/templates/quick_money.html
{% load static %}
{% load django_tables2 %}


{% block head %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cyborg/bootstrap.min.css"
      integrity="sha384-nEnU7Ae+3lD52AK+RGNzgieBWMnEfgTbRHIwEvp1XXPdqdO6uLTd/NwXbzboqjc2" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
{% csrf_token %}
{%include 'navbar.html' %}
{% endblock %}
{% for table in tables %}
{% render_table table %}
{% endfor %}
{{ items }}

osrs_site/prices/templates/single_table.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="ui container table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="ui celled table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                    <tr>
                    {% for column in table.columns %}
                        <th {{ column.attrs.th.as_html }}>
                            {% if column.orderable %}
                                <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                            {% else %}
                                {{ column.header }}
                            {% endif %}
                        </th>
                    {% endfor %}
                    </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                        <a href={% url 'single_table' item_name=cell %}>
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        </a>
                        {% endfor %}

                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                    <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                {% if table.has_footer %}
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
                {% endif %}
                {% block pagination %}
                    {% if table.page and table.paginator.num_pages > 1 %}
                    <tr>
                    <th colspan="{{ table.columns|length }}">
                        <div class="ui right floated pagination menu">

                            <ul class="pagination">
                            {% if table.page.has_previous %}
                                {% block pagination.previous %}
                                <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                                    &laquo;
                                </a>
                                {% endblock pagination.previous %}
                            {% endif %}

                            {% if table.page.has_previous or table.page.has_next %}
                                {% block pagination.range %}
                                    {% for p in table.page|table_page_range:table.paginator %}
                                        {% if p == '...' %}
                                            <a href="#" class="item">{{ p }}</a>
                                        {% else %}
                                            <li class="page-item {% if p == table.page.number %}active{% endif %}">
                                            <a href="{% querystring table.prefixed_page_field=p %}" class="page-link">
                                                {{ p }}
                                            </a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                {% endblock pagination.range %}
                            {% endif %}

                            {% if table.page.has_next %}
                                {% block pagination.next %}
                                <li class="page-item">
                                <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                                    &raquo;
                                </a>
                                </li>
                                {% endblock pagination.next %}
                            {% endif %}
                        </div>
                    </th>
                    </tr>
                    {% endif %}
                </ul>
                {% endblock pagination %}
            </tfoot>
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}
</div>
{% endblock table-wrapper %}

osrs_site/prices/templates/table.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="ui container table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="ui celled table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                    <tr>
                    {% for column in table.columns %}
                        <th {{ column.attrs.th.as_html }}>
                            {% if column.orderable %}
                                <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                            {% else %}
                                {{ column.header }}
                            {% endif %}
                        </th>
                    {% endfor %}
                    </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                    <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                {% if table.has_footer %}
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
                {% endif %}
                {% block pagination %}
                    {% if table.page and table.paginator.num_pages > 1 %}
                    <tr>
                    <th colspan="{{ table.columns|length }}">
                        <div class="ui right floated pagination menu">

                            <ul class="pagination">
                            {% if table.page.has_previous %}
                                {% block pagination.previous %}
                                <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                                    &laquo;
                                </a>
                                {% endblock pagination.previous %}
                            {% endif %}

                            {% if table.page.has_previous or table.page.has_next %}
                                {% block pagination.range %}
                                    {% for p in table.page|table_page_range:table.paginator %}
                                        {% if p == '...' %}
                                            <a href="#" class="item">{{ p }}</a>
                                        {% else %}
                                            <li class="page-item {% if p == table.page.number %}active{% endif %}">
                                            <a href="{% querystring table.prefixed_page_field=p %}" class="page-link">
                                                {{ p }}
                                            </a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                {% endblock pagination.range %}
                            {% endif %}

                            {% if table.page.has_next %}
                                {% block pagination.next %}
                                <li class="page-item">
                                <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                                    &raquo;
                                </a>
                                </li>
                                {% endblock pagination.next %}
                            {% endif %}
                        </div>
                    </th>
                    </tr>
                    {% endif %}
                </ul>
                {% endblock pagination %}
            </tfoot>
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}
</div>
{% endblock table-wrapper %}